# syntax=docker/dockerfile:1
# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

################################################################################

ARG ENROOT_VERSION=3.5.0
ARG PYXIS_VERSION=0.20.0

################################################################################
FROM ghcr.io/slinkyproject/slurmd:24.11-ubuntu24.04 AS download

SHELL ["bash", "-c"]

ARG DEBIAN_FRONTEND=noninteractive

USER root
WORKDIR /tmp/

ARG TARGETARCH
ARG ENROOT_VERSION
ENV ENROOT_VERSION="${ENROOT_VERSION}"

ADD https://github.com/NVIDIA/enroot/releases/download/v${ENROOT_VERSION}/enroot_${ENROOT_VERSION}-1_${TARGETARCH}.deb enroot_${ENROOT_VERSION}-1_${TARGETARCH}.deb
ADD https://github.com/NVIDIA/enroot/releases/download/v${ENROOT_VERSION}/enroot+caps_${ENROOT_VERSION}-1_${TARGETARCH}.deb enroot+caps_${ENROOT_VERSION}-1_${TARGETARCH}.deb

ARG PYXIS_VERSION
ENV PYXIS_VERSION="${PYXIS_VERSION}"

ADD https://github.com/NVIDIA/pyxis/archive/refs/tags/v${PYXIS_VERSION}.tar.gz pyxis-v${PYXIS_VERSION}.tar.gz

# Ref: https://github.com/NVIDIA/pyxis?tab=readme-ov-file#with-a-deb-package
# Ref: https://github.com/NVIDIA/enroot/blob/master/doc/installation.md
RUN <<EOR
# Generate Pyxis DEB
set -xeuo pipefail
apt-get -qq update
apt-get -qq -y install --no-install-recommends \
  build-essential \
  git gcc make libcap2-bin libtool automake libmd-dev \
  fakeroot devscripts equivs \
  tar
tar -zxvf pyxis-v${PYXIS_VERSION}.tar.gz
cd pyxis-${PYXIS_VERSION}
make orig
make deb
apt-get clean && rm -rf /var/lib/apt/lists/*
EOR

################################################################################
# SLURM: slurmd-pyxis
# BUILD: `docker build --target=slurmd-pyxis -t [<registry>/]slurmd-pyxis:<tag> .`
################################################################################
FROM ghcr.io/slinkyproject/slurmd:24.11-ubuntu24.04 AS slurmd-pyxis

ARG DEBIAN_FRONTEND=noninteractive

ARG ENROOT_VERSION
ENV ENROOT_VERSION="${ENROOT_VERSION}"

ARG PYXIS_VERSION
ENV PYXIS_VERSION="${PYXIS_VERSION}"

COPY --from=download /tmp/*.deb ./

# Ref: https://github.com/NVIDIA/pyxis?tab=readme-ov-file#with-a-deb-package
# Ref: https://github.com/NVIDIA/enroot/blob/master/doc/installation.md
RUN <<EOR
# Install Pyxis+Enroot
set -xeuo pipefail
apt-get -qq update
apt-get -qq -y upgrade
apt-get -qq -y install --no-install-recommends --fix-broken \
  ca-certificates gpg \
  bash-completion \
  fuse-overlayfs pigz squashfuse \
  ./*.deb
rm *.deb && apt-get clean && rm -rf /var/lib/apt/lists/*
# Configure
mkdir -m 777 -p /usr/share/enroot/enroot-data/
mkdir -m 755 -p /run/enroot/
mkdir -m 644 -p /etc/slurm/plugstack.conf.d/
ln -s /usr/share/pyxis/pyxis.conf /etc/slurm/plugstack.conf.d/pyxis.conf
EOR

ADD https://raw.githubusercontent.com/NVIDIA/enroot/refs/tags/v${ENROOT_VERSION}/conf/bash_completion /usr/share/bash-completion/completions/enroot
ADD https://raw.githubusercontent.com/NVIDIA/enroot/refs/tags/v${ENROOT_VERSION}/conf/hooks/extra/50-mig-config.sh /etc/enroot/hooks.d/50-mig-config.sh
ADD https://raw.githubusercontent.com/NVIDIA/enroot/refs/tags/v${ENROOT_VERSION}/conf/hooks/extra/50-sharp.sh /etc/enroot/hooks.d/50-sharp.sh
ADD https://raw.githubusercontent.com/NVIDIA/enroot/refs/tags/v${ENROOT_VERSION}/conf/hooks/extra/50-slurm-pmi.sh /etc/enroot/hooks.d/50-slurm-pmi.sh
ADD https://raw.githubusercontent.com/NVIDIA/enroot/refs/tags/v${ENROOT_VERSION}/conf/hooks/extra/50-slurm-pytorch.sh /etc/enroot/hooks.d/50-slurm-pytorch.sh

RUN chmod 755 -R /etc/enroot/hooks.d/

ADD https://nvidia.github.io/libnvidia-container/gpgkey libnvidia-container.gpgkey
ADD https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list /etc/apt/sources.list.d/nvidia-container-toolkit.list

# Ref: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#with-apt-ubuntu-debian
RUN <<EOR
# Install Nvidia Container Toolkit
set -xeuo pipefail
gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg ./libnvidia-container.gpgkey
sed -i 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' /etc/apt/sources.list.d/nvidia-container-toolkit.list
apt-get -qq update
apt-get -qq -y install --no-install-recommends \
  nvidia-container-toolkit
rm *.gpgkey && apt-get clean && rm -rf /var/lib/apt/lists/*

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y \
  aria2 \
  build-essential \
  clustershell \
  cmake \
  colordiff \
  dnsutils \
  emacs \
  expect \
  git \
  gzip \
  htop \
  infiniband-diags \
  iotop \
  iproute2 \
  mawk \
  mc \
  mosh \
  nvtop \
  parallel \
  pigz \
  python3-numpy \
  python3-pip \
  python3-venv \
  rclone \
  redis \
  ripgrep \
  rsync \
  screen \
  sed \
  sudo \
  tmux \
  tree \
  unzip \
  vim \
  wget \
  xz-utils \
  zip \
  zsh

wget https://github.com/cli/cli/releases/download/v2.50.0/gh_2.50.0_linux_amd64.deb && \
    dpkg -i gh_2.50.0_linux_amd64.deb && \
    rm gh_2.50.0_linux_amd64.deb

wget -q https://aka.ms/InstallAzureCLIDeb && \
    bash InstallAzureCLIDeb && \
    rm InstallAzureCLIDeb

wget -q https://aka.ms/downloadazcopy-v10-linux -O azcopy_v10.tar.gz && \
    mkdir azcopy && \
    tar -xf azcopy_v10.tar.gz -C ./azcopy --strip-components=1 && \
    mv ./azcopy/azcopy /usr/local/bin/ && \
    rm -r azcopy_v10.tar.gz ./azcopy

wget -q https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64 -O /usr/local/bin/yq && \
    chmod +x /usr/local/bin/yq

# this is the canonical way of installing uv; currently forcing fixed version
curl -LsSf https://astral.sh/uv/0.7.4/install.sh | env UV_INSTALL_DIR="/usr/bin" sh
EOR

################################################################################
# SLURM: login-pyxis
# BUILD: `docker build --target=login-pyxis -t [<registry>/]login-pyxis:<tag> .`
################################################################################
FROM ghcr.io/slinkyproject/login:24.11-ubuntu24.04 AS login-pyxis

ARG DEBIAN_FRONTEND=noninteractive

ARG ENROOT_VERSION
ENV ENROOT_VERSION="${ENROOT_VERSION}"

ARG PYXIS_VERSION
ENV PYXIS_VERSION="${PYXIS_VERSION}"

COPY --from=download /tmp/*.deb ./

# Ref: https://github.com/NVIDIA/pyxis?tab=readme-ov-file#with-a-deb-package
# Ref: https://github.com/NVIDIA/enroot/blob/master/doc/installation.md
RUN <<EOR
# Install Pyxis+Enroot
set -xeuo pipefail
apt-get -qq update
apt-get -qq -y upgrade
apt-get -qq -y install --no-install-recommends --fix-broken \
  ca-certificates gpg \
  bash-completion \
  fuse-overlayfs pigz squashfuse \
  ./*.deb
rm *.deb && apt-get clean && rm -rf /var/lib/apt/lists/*
# Configure
mkdir -m 777 -p /usr/share/enroot/enroot-data/
mkdir -m 755 -p /run/enroot/
mkdir -m 644 -p /etc/slurm/plugstack.conf.d/
ln -s /usr/share/pyxis/pyxis.conf /etc/slurm/plugstack.conf.d/pyxis.conf
EOR

ADD https://raw.githubusercontent.com/NVIDIA/enroot/refs/tags/v${ENROOT_VERSION}/conf/bash_completion /usr/share/bash-completion/completions/enroot
ADD https://raw.githubusercontent.com/NVIDIA/enroot/refs/tags/v${ENROOT_VERSION}/conf/hooks/extra/50-mig-config.sh /etc/enroot/hooks.d/50-mig-config.sh
ADD https://raw.githubusercontent.com/NVIDIA/enroot/refs/tags/v${ENROOT_VERSION}/conf/hooks/extra/50-sharp.sh /etc/enroot/hooks.d/50-sharp.sh
ADD https://raw.githubusercontent.com/NVIDIA/enroot/refs/tags/v${ENROOT_VERSION}/conf/hooks/extra/50-slurm-pmi.sh /etc/enroot/hooks.d/50-slurm-pmi.sh
ADD https://raw.githubusercontent.com/NVIDIA/enroot/refs/tags/v${ENROOT_VERSION}/conf/hooks/extra/50-slurm-pytorch.sh /etc/enroot/hooks.d/50-slurm-pytorch.sh

RUN chmod 755 -R /etc/enroot/hooks.d/

ADD https://nvidia.github.io/libnvidia-container/gpgkey libnvidia-container.gpgkey
ADD https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list /etc/apt/sources.list.d/nvidia-container-toolkit.list

# Ref: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#with-apt-ubuntu-debian
RUN <<EOR
# Install Nvidia Container Toolkit
set -xeuo pipefail
gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg ./libnvidia-container.gpgkey
sed -i 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' /etc/apt/sources.list.d/nvidia-container-toolkit.list
apt-get -qq update
apt-get -qq -y install --no-install-recommends \
  nvidia-container-toolkit
rm *.gpgkey && apt-get clean && rm -rf /var/lib/apt/lists/*


export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y \
  aria2 \
  build-essential \
  clustershell \
  cmake \
  colordiff \
  dnsutils \
  emacs \
  expect \
  git \
  gzip \
  htop \
  infiniband-diags \
  iotop \
  iproute2 \
  mawk \
  mc \
  mosh \
  nvtop \
  parallel \
  pigz \
  python3-numpy \
  python3-pip \
  python3-venv \
  rclone \
  redis \
  ripgrep \
  rsync \
  screen \
  sed \
  sudo \
  tmux \
  tree \
  unzip \
  vim \
  wget \
  xz-utils \
  zip \
  zsh

wget https://github.com/cli/cli/releases/download/v2.50.0/gh_2.50.0_linux_amd64.deb && \
    dpkg -i gh_2.50.0_linux_amd64.deb && \
    rm gh_2.50.0_linux_amd64.deb

wget -q https://aka.ms/InstallAzureCLIDeb && \
    bash InstallAzureCLIDeb && \
    rm InstallAzureCLIDeb

wget -q https://aka.ms/downloadazcopy-v10-linux -O azcopy_v10.tar.gz && \
    mkdir azcopy && \
    tar -xf azcopy_v10.tar.gz -C ./azcopy --strip-components=1 && \
    mv ./azcopy/azcopy /usr/local/bin/ && \
    rm -r azcopy_v10.tar.gz ./azcopy

wget -q https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64 -O /usr/local/bin/yq && \
    chmod +x /usr/local/bin/yq

# this is the canonical way of installing uv; currently forcing fixed version
curl -LsSf https://astral.sh/uv/0.7.4/install.sh | env UV_INSTALL_DIR="/usr/bin" sh


EOR
